env: dev

http:
  host: "0.0.0.0"
  port: "8082"

fakestore:
  host: "product-server-dev-qb02m9.5sc6y6-3.usa-e2.cloudhub.io"
  port: "443"
  protocol: "HTTPS"

salesforce:
  host: "product-salesforce-system-dev-qb02m9.5sc6y6-3.usa-e2.cloudhub.io"
  port: "443"
  protocol: "HTTPS"
